/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import Principal.LiberarMemoria;
import conexionBBDD.Consulta;
import conexionBBDD.Gestion_Datos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dam
 */
public class Form_Mensajes_Usuario extends javax.swing.JFrame {

    private Connection c;

    /**
     * Creates new form Form_Mensajes_Usuario
     */
    public Form_Mensajes_Usuario(Connection c) {
        initComponents();
        this.c = c;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mensajes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_nick = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_mensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mensaje", "Hora", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_mensajes);

        jLabel1.setText("Nick");

        btn_buscar.setText("Buscar");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_buscar)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        // TODO add your handling code here:
        Gestion_Datos gd = new Gestion_Datos(c);
        try {
            loadData(gd.buscar_mensajes(txt_nick.getText()));
        } catch (SQLException ex) {
            Logger.getLogger(Form_Mensajes_Usuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        LiberarMemoria.pasarGarbageCollector();
    }//GEN-LAST:event_btn_buscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_mensajes;
    private javax.swing.JTextField txt_nick;
    // End of variables declaration//GEN-END:variables

    private void loadData(Consulta consulta) throws SQLException {

        DefaultTableModel tm = (DefaultTableModel) tbl_mensajes.getModel();
        tm.getDataVector().removeAllElements();
        if (consulta == null || !consulta.getResultado().next()) {
            Gestion_Datos gd = new Gestion_Datos(c);
            String columnas[] = {"Mensaje", "Hora", "Fecha"};
            gd.borrar_tabla(tbl_mensajes, columnas);
            LiberarMemoria.pasarGarbageCollector();
        } else {
            consulta.getResultado().absolute(0);
            while (consulta.getResultado().next()) {
                Object[] rowData = new Object[3];

                rowData[0] = consulta.getResultado().getString(1);
                rowData[1] = consulta.getResultado().getTime(2);
                rowData[2] = consulta.getResultado().getDate(3);

                tm.addRow(rowData);
            }
        }

    }
}
