/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import conexionBBDD.Consulta;
import conexionBBDD.Gestion_Datos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Ordóñez Vázquez
 */
public class Form_Mensajes extends javax.swing.JFrame {
    private Connection c;
    /**
     * Creates new form Mensajes
     */
    public Form_Mensajes(Connection c) throws SQLException {
        initComponents();
        this.c = c;
        this.setLocationRelativeTo(null);
        Consulta consulta = new Consulta(c, "select * from mensaje");
        loadData(consulta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_mensajes = new javax.swing.JTable();
        btn_escribir = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_mensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Mensaje", "Hora", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_mensajes);
        if (tbl_mensajes.getColumnModel().getColumnCount() > 0) {
            tbl_mensajes.getColumnModel().getColumn(0).setMinWidth(5);
            tbl_mensajes.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbl_mensajes.getColumnModel().getColumn(1).setMinWidth(5);
            tbl_mensajes.getColumnModel().getColumn(1).setPreferredWidth(5);
        }

        btn_escribir.setText("Escribir mensaje");
        btn_escribir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_escribirMouseClicked(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });

        btn_actualizar.setText("Refrescar");
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });

        btn_borrar.setText("Borrar");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btn_escribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btn_borrar)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizar)
                .addGap(29, 29, 29)
                .addComponent(btn_salir)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_escribir)
                    .addComponent(btn_borrar)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_salir))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        // TODO add your handling code here:
        Consulta consulta;
        try {
            consulta = new Consulta(c, "select * from mensaje");
            DefaultTableModel tm = (DefaultTableModel) tbl_mensajes.getModel();
            tm.getDataVector().removeAllElements();
            loadData(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(Form_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_escribirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_escribirMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Escribir_Mensaje form = new Form_Escribir_Mensaje(c);
                form.setVisible(true);
                form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                form.setTitle("Publicar Mensaje");
            }
        });
    }//GEN-LAST:event_btn_escribirMouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel) tbl_mensajes.getModel();
        if (tbl_mensajes.getSelectedRow() != -1) {
            try {
                Gestion_Datos gd = new Gestion_Datos(c);
                gd.borrar_mensaje((int)tm.getValueAt(tbl_mensajes.getSelectedRow(), 0));
                tm.removeRow(tbl_mensajes.getSelectedRow());
            } catch (SQLException ex) {
                Logger.getLogger(Form_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void loadData(Consulta consulta) throws SQLException {

        DefaultTableModel tm = (DefaultTableModel) tbl_mensajes.getModel();

        while (consulta.getResultado().next()) {
            Object[] rowData = new Object[5];
            
            rowData[0] = consulta.getResultado().getInt(1);
            rowData[1] = consulta.getResultado().getInt(2);
            rowData[2] = consulta.getResultado().getString(3);
            rowData[3] = consulta.getResultado().getTime(4);
            rowData[4] = consulta.getResultado().getDate(5);
            
            tm.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_escribir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_mensajes;
    // End of variables declaration//GEN-END:variables
}
