/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import Principal.LiberarMemoria;
import conexionBBDD.Consulta;
import conexionBBDD.Gestion_Datos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Ordóñez Vázquez
 */
public class Form_Seguidores extends javax.swing.JFrame {
    private Connection c;
    /**
     * Creates new form Form_Seguidores
     */
    public Form_Seguidores(Connection c) throws SQLException {
        initComponents();
        this.c = c;
        Consulta consulta = new Consulta(c, "select * from seguir");
        loadData(consulta);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_seguir = new javax.swing.JTable();
        btn_seguir = new javax.swing.JButton();
        btn_refrescar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_mostrar_seguidores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_seguir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Sigue a"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_seguir);

        btn_seguir.setText("Seguir ");
        btn_seguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seguirMouseClicked(evt);
            }
        });

        btn_refrescar.setText("Refrescar");
        btn_refrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refrescarMouseClicked(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });

        btn_borrar.setText("Dejar de seguir");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });

        btn_mostrar_seguidores.setText("Buscar Seguidores");
        btn_mostrar_seguidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrar_seguidoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_seguir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_borrar)
                .addGap(36, 36, 36)
                .addComponent(btn_refrescar)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btn_mostrar_seguidores)
                .addGap(48, 48, 48)
                .addComponent(btn_salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_borrar)
                    .addComponent(btn_refrescar)
                    .addComponent(btn_seguir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mostrar_seguidores)
                    .addComponent(btn_salir))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_refrescarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refrescarMouseClicked
        // TODO add your handling code here:
        Consulta consulta;
        try {
            consulta = new Consulta(c, "select * from seguir");
            DefaultTableModel tm = (DefaultTableModel) tbl_seguir.getModel();
            tm.getDataVector().removeAllElements();
            loadData(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(Form_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_refrescarMouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        try {
            // TODO add your handling code here:
            Gestion_Datos gd = new Gestion_Datos(c);
            gd.dejar_de_seguir(tbl_seguir, "delete from seguir where id_seguir = ?");
            LiberarMemoria.pasarGarbageCollector();
        } catch (SQLException ex) {
            Logger.getLogger(Form_Seguidores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void btn_seguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seguirMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Insertar_Seguir form = new Form_Insertar_Seguir(c);
                form.setVisible(true);
                form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                form.setTitle("Seguir Usuario");
            }
        });
    }//GEN-LAST:event_btn_seguirMouseClicked

    private void btn_mostrar_seguidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrar_seguidoresMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Seguidores_De form = new Form_Seguidores_De(c);
                form.setVisible(true);
                form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                form.setTitle("Buscar Seguidores");
            }
        });
    }//GEN-LAST:event_btn_mostrar_seguidoresMouseClicked
    
    private void loadData(Consulta consulta) throws SQLException {

        DefaultTableModel tm = (DefaultTableModel) tbl_seguir.getModel();

        while (consulta.getResultado().next()) {
            Object[] rowData = new Object[3];
            
            rowData[0] = consulta.getResultado().getInt(1);
            rowData[1] = consulta.getResultado().getInt(2);
            rowData[2] = consulta.getResultado().getInt(3);
            
            tm.addRow(rowData);
        }
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_mostrar_seguidores;
    private javax.swing.JButton btn_refrescar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_seguir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_seguir;
    // End of variables declaration//GEN-END:variables
}
