/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import Principal.LiberarMemoria;
import conexionBBDD.Consulta;
import conexionBBDD.Gestion_Datos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import tablas.Usuario;

/**
 *
 * @author dam
 */
public class Form_Usuarios extends javax.swing.JFrame {

    private Connection c;

    /**
     * Creates new form Form_Usuarios
     */
    public Form_Usuarios(Connection c) throws SQLException {
        initComponents();
        this.c = c;
        this.setLocationRelativeTo(null);
        Consulta consulta = new Consulta(c, "select * from usuario");
        loadData(consulta);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        btn_insertar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_delete_nick = new javax.swing.JButton();
        btn_mostrarmsg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nick", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_usuarios);
        if (tbl_usuarios.getColumnModel().getColumnCount() > 0) {
            tbl_usuarios.getColumnModel().getColumn(0).setPreferredWidth(2);
        }

        btn_insertar.setText("Insertar");
        btn_insertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_insertarMouseClicked(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });

        btn_actualizar.setText("Refrescar");
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });

        btn_borrar.setText("Borrar");
        btn_borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_borrarMouseClicked(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editarMouseClicked(evt);
            }
        });

        btn_delete_nick.setText("Borrar por nick");
        btn_delete_nick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_delete_nickMouseClicked(evt);
            }
        });

        btn_mostrarmsg.setText("Buscar mensajes");
        btn_mostrarmsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mostrarmsgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_insertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_borrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(btn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_salir)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btn_delete_nick)
                .addGap(26, 26, 26)
                .addComponent(btn_mostrarmsg)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_insertar)
                    .addComponent(btn_salir)
                    .addComponent(btn_actualizar)
                    .addComponent(btn_borrar)
                    .addComponent(btn_editar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete_nick)
                    .addComponent(btn_mostrarmsg))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_insertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_insertarMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Insertar_Usuario form = new Form_Insertar_Usuario(c);
                form.setVisible(true);
                form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                form.setTitle("Registrar Usuario");
            }
        });
    }//GEN-LAST:event_btn_insertarMouseClicked

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        // TODO add your handling code here:
        Consulta consulta;
        try {
            consulta = new Consulta(c, "select * from usuario");
            DefaultTableModel tm = (DefaultTableModel) tbl_usuarios.getModel();
            tm.getDataVector().removeAllElements();
            loadData(consulta);
        } catch (SQLException ex) {
            Logger.getLogger(Form_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_borrarMouseClicked
        // TODO add your handling code here:
        Gestion_Datos gd = new Gestion_Datos(c);
        gd.borrar_registro_usuario(tbl_usuarios, "select pass from usuario where id_usuario = ");
        LiberarMemoria.pasarGarbageCollector();
    }//GEN-LAST:event_btn_borrarMouseClicked

    private void btn_editarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editarMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int posicion = tbl_usuarios.getSelectedRow();
                if (posicion != -1) {
                    try {
                        DefaultTableModel tm = (DefaultTableModel) tbl_usuarios.getModel();
                       
                        Form_Insertar_Usuario form = new Form_Insertar_Usuario(c, posicion, 
                                new Consulta(c, "select * from usuario where id_usuario = " + ((int) tm.getValueAt(posicion, 0))));
                        form.setVisible(true);
                        form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                        form.setTitle("Modificar Usuario");
                    } catch (SQLException ex) {
                        Logger.getLogger(Form_Usuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }//GEN-LAST:event_btn_editarMouseClicked

    private void btn_delete_nickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_delete_nickMouseClicked
        // TODO add your handling code here:
        Gestion_Datos gd = new Gestion_Datos(c);
        gd.borrar_usuario_nick();
        LiberarMemoria.pasarGarbageCollector();
    }//GEN-LAST:event_btn_delete_nickMouseClicked

    private void btn_mostrarmsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mostrarmsgMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Mensajes_Usuario form = new Form_Mensajes_Usuario(c);
                form.setVisible(true);
                form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                form.setTitle("Buscar Mensajes");
            }
        });
    }//GEN-LAST:event_btn_mostrarmsgMouseClicked

    private void loadData(Consulta consulta) throws SQLException {

        DefaultTableModel tm = (DefaultTableModel) tbl_usuarios.getModel();

        while (consulta.getResultado().next()) {
            Object[] rowData = new Object[3];

            rowData[0] = consulta.getResultado().getInt(1);
            rowData[1] = consulta.getResultado().getString(2);
            rowData[2] = consulta.getResultado().getString(3);

            tm.addRow(rowData);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_delete_nick;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_insertar;
    private javax.swing.JButton btn_mostrarmsg;
    private javax.swing.JButton btn_salir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_usuarios;
    // End of variables declaration//GEN-END:variables
}
