/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import Principal.LiberarMemoria;
import conexionBBDD.Consulta;
import conexionBBDD.Gestion_Datos;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Ordóñez Vázquez
 */
public class Form_Seguidores_De extends javax.swing.JFrame {

    private Connection c;

    /**
     * Creates new form Form_Seguidores_De
     */
    public Form_Seguidores_De(Connection c) {
        initComponents();
        this.c = c;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_seguidoresDe = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_nick = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        cb_opciones = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_seguidoresDe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_seguidoresDe);

        jLabel1.setText("Usuario");

        btn_buscar.setText("Buscar ");
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        cb_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seguidores", "Usuarios seguidos" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_nick, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(cb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btn_buscar)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(cb_opciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        // TODO add your handling code here:
        Gestion_Datos gd = new Gestion_Datos(c);
        try {
            loadData(gd.buscar_seguidores(txt_nick.getText(), cb_opciones.getSelectedItem().toString()));
        } catch (SQLException ex) {
            Logger.getLogger(Form_Seguidores_De.class.getName()).log(Level.SEVERE, null, ex);
        }
        LiberarMemoria.pasarGarbageCollector();
    }//GEN-LAST:event_btn_buscarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JComboBox<String> cb_opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_seguidoresDe;
    private javax.swing.JTextField txt_nick;
    // End of variables declaration//GEN-END:variables
private void loadData(Consulta consulta) throws SQLException {
        DefaultTableModel tm = (DefaultTableModel) tbl_seguidoresDe.getModel();
        tm.getDataVector().removeAllElements();
        if (consulta == null || !consulta.getResultado().next()) {
            Gestion_Datos gd = new Gestion_Datos(c);
            String [] columnas = {"Usuarios"};
            gd.borrar_tabla(tbl_seguidoresDe, columnas);
            LiberarMemoria.pasarGarbageCollector();
        } else {
            consulta.getResultado().absolute(0);
            while (consulta.getResultado().next()) {
                Object[] rowData = new Object[1];
                rowData[0] = consulta.getResultado().getString(1);
                tm.addRow(rowData);
            }
        }
    }
}
