/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazGrafica;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author dam
 */
public class Ventana_Principal extends javax.swing.JFrame {
    private Connection c;
    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_Principal(Connection c) {
        this.c = c;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_mensajes = new javax.swing.JButton();
        btn_seguidores = new javax.swing.JButton();
        btn_pass = new javax.swing.JButton();
        btn_usuariosv2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btn_mensajes.setText("Mensajes");
        btn_mensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mensajesMouseClicked(evt);
            }
        });

        btn_seguidores.setText("Seguidores");
        btn_seguidores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_seguidoresMouseClicked(evt);
            }
        });

        btn_pass.setText("Contraseñas");
        btn_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_passMouseClicked(evt);
            }
        });

        btn_usuariosv2.setText("Usuarios");
        btn_usuariosv2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_usuariosv2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_seguidores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(btn_pass))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_usuariosv2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_mensajes)))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mensajes)
                    .addComponent(btn_usuariosv2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pass)
                    .addComponent(btn_seguidores))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mensajesMouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Form_Mensajes form = new Form_Mensajes(c);
                    form.setVisible(true);
                    form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    form.setTitle("Mensajes");
                } catch (SQLException ex) {
                    Logger.getLogger(Ventana_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_btn_mensajesMouseClicked

    private void btn_seguidoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seguidoresMouseClicked
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Form_Seguidores form = new Form_Seguidores(c);
                    form.setVisible(true);
                    form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    form.setTitle("Seguidores");
                } catch (SQLException ex) {
                    Logger.getLogger(Ventana_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_btn_seguidoresMouseClicked

    private void btn_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_passMouseClicked
        // TODO add your handling code here:
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Form_Passwords form = new Form_Passwords(c);
                    form.setVisible(true);
                    form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    form.setTitle("Contraseñas");
                } catch (SQLException ex) {
                    Logger.getLogger(Ventana_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_btn_passMouseClicked

    private void btn_usuariosv2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosv2MouseClicked
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Form_Usuarios form = new Form_Usuarios(c);
                    form.setVisible(true);
                    form.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                    form.setTitle("Usuarios");
                } catch (SQLException ex) {
                    Logger.getLogger(Ventana_Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_btn_usuariosv2MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            // TODO add your handling code here:
            c.close();
        } catch (SQLException ex) {
            Logger.getLogger(Ventana_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mensajes;
    private javax.swing.JButton btn_pass;
    private javax.swing.JButton btn_seguidores;
    private javax.swing.JButton btn_usuariosv2;
    // End of variables declaration//GEN-END:variables
}
